[functions]
node_bundler = "esbuild"

[dev]
port = 8989
publish = "public"

[build]
command = "# no build command"
# command = "npm run build"
functions = "netlify/functions"
publish = "public"

#[[headers]]
#    for = "/*"
#    [headers.values]
#        access-control-allow-origin="*"
